services:
  db:
    image: pgvector/pgvector:pg18-trixie
    container_name: redlineiq-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: redlineiq
      POSTGRES_PASSWORD: redlineiq
    ports:
      - "5432:5432"
    volumes:
      - redlineiq_pgdata:/var/lib/postgresql
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U redlineiq -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: redlineiq-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      API_TITLE: RedlineIQ API
      API_VERSION: 0.1.0

      DATABASE_URL: postgresql+psycopg2://redlineiq:redlineiq@db:5432/redlineiq
      SQL_SCHEMA_PATH: /app/pipelines/db_schema/redlineiq_schema.sql
      CLEANED_DATA_DIR: /app/data/cleaned


      FRONTEND_ORIGINS: http://localhost:3000,http://localhost:5173,http://localhost:8080

      LLM_PROVIDER: gemini
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL:-gemini-3.5-flash}

      EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
      EMBEDDING_DIM: 384
      EMBEDDING_BATCH_SIZE: 32
      MAX_EMBED_CHUNKS: 250000

      LLM_TEMPERATURE: 0.2
      LLM_MAX_OUTPUT_TOKENS: 1200
      LLM_TIMEOUT_SECONDS: 120

      PROMPT_VERSION: redlineiq_rag_v1
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/pipelines:/app/pipelines
      - ./data/cleaned:/app/data/cleaned
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  
  frontend:
    build:
      context: ./Frontend/app
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
      
    container_name: redlineiq-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  redlineiq_pgdata:
  